### ISSUE TITLE
Invalid hreflang urls generated for urls with path folders nested 2 levels or more

### ISSUE THREAD

**Issue by bblimke** [weglot/integration-hooks#3]
When we run the script and there are pages with folders nested 2 levels or more, the script generates incorrect hreflang urls:

E.g url:
````
https://www.example.com/integrations/drupal
````
will get the following hreflangs generated
````
https://www.example.com/detail_integrations
https://fr.example.com/detail_integrations
https://de.example.com/detail_integrations
....
````

**Comment by bblimke** [comment]
btw. does the script overwrite existing tags? e.g if it's fixed, will it only add new fixed tags or will it overwrite broken tags?

**Comment by nico2che** [comment]
Hi @bblimke, thank you for your feedback!

Interesting case, you're right about nested levels and I made a fix about this

I think `detail_integration` isn't a common slug, like `detail_post` or `detail_product` which will be dynamically generated by Webflow, I tried to fix this, can you test it?

**Comment by nico2che** [comment]
And if you run this script again it will override all head scripts, is this a problem?

**Comment by bblimke** [comment]
@nico2che thank you!

Yes, the fix seems to have worked. Excellent.

> And if you run this script again it will override all head scripts, is this a problem?

That is desired. Thank you.

One question. Are paths in the urls supposed to be translated as well or not? They are not being translated,
and perhaps that's how it should be, but I'm wondering.

**Comment by nico2che** [comment]
It's not implemented
Are you using the slug translation Weglot feature? if yes, I'll see to do that next

**Comment by bblimke** [comment]
yes, we do use Weglot slug translation. Thanks :)

**Comment by nico2che** [comment]
nice, can you test the last version please? it should work with translated slugs now

**Comment by bblimke** [comment]
@nico2che thank you!

almost there :)

now if we have `https://www.example.com/level_1/level_2` it will translate `level_1` but not `level_2`

**Comment by nico2che** [comment]
You're right and it seems to be difficult to do more because the second level is dynamically generated by Webflow, the script injects a Webflow snippet like `/integraciones/{{wf {"path":"slug","type":"PlainText"} }}`, so I can't translate this part, sorry for this

However, translated or half-translated, all links should be work and redirect to the most translated one, search engine bots like Google bot will save the translated one.

**Comment by bblimke** [comment]
I understand the problem. I can also confirm that despite the second level is not translated, it does indeed redirect to the correctly translated url with whole path translated.

Thank you!
