### ISSUE TITLE
Squarespace: Receiving error "Some config is missing"

### ISSUE THREAD

**Issue by JustinBEverett** [weglot/integration-hooks#4]
Hello,

I'm receiving the error "Some config is missing" when attempting to run `node squarespace/hook.js`

Here is my config.js with password removed (I have 2FA turned on so I've tried both my actual password and a Squarespace generate app password.):

```
module.exports = {
  apiKey: "", // weglot api_key

  originalHost: "https://www.chancho.ca/",
  translatedHost: "https://es.chancho.ca/",

  originalLanguage: "en",
  languages: ["es"],

  projectName: "chancho-yvr", // url slug

  user: "justin@justineverett.ca",
  password: "###########################"
};
```

Am I missing something?

**Comment by roptch** [comment]
Hello !
The "Some config is missing" error message means that there is a config field that is empty.
There are 2 possibilities:
* I see in your `config.js` file that the `apiKey` field is empty, was it empty during your tests ?
* The `user` and `password` fields need to be in `squarespace/config.js` and not in the root `config.js` (it is not very clearly explained, we will change this behavior)

Hope this helps you !
