### ISSUE TITLE
URL not translated when there is 2 slug

### ISSUE THREAD

**Issue by remyberda** [weglot/integration-hooks#6]
Un client avait /rate/call-india et a traduit rate => tarifs et call-india => appeler-l-inde

Mais il semble qu'on lui mette le hreflang /tarif/call-india
en gros on mixe les deux langues

Voir : https://secure.helpscout.net/conversation/1670015136/199339?folderId=2481524

Page : https://www.talk360.com/rates/call-india

**Comment by nico2che** [comment]
outdated
