### ISSUE TITLE
Not working in webflow: Cannot read property 'collections' of undefined

### ISSUE THREAD

**Issue by arielcamino** [weglot/integration-hooks#7]
This is what I'm getting when running:

```
❯ node webflow/hook.js
Searching for CSRF Token...
CSRF found!

Get Webflow pages...
OK
/Users/acamino/repos/salesql/webflow/integration-hooks/webflow/hook.js:120
    console.log(`\nUpdating ${dom.database.collections.length} collections...`);
                                           ^

TypeError: Cannot read property 'collections' of undefined
    at /Users/acamino/repos/salesql/webflow/integration-hooks/webflow/hook.js:120:44
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```
it looks like the property "collections" does not exist in the response from the API endpoint.

Not sure how to replicate this call to see what's wrong with the response.

**Comment by nico2che** [comment]
Thank you for your feedback!

**Comment by arielcamino** [comment]
Hi @nico2che, this is not feedback, it's an issue running this on Webflow. It looks like the documentation and code is outdated, the URL indicated in the documentation does not even exist:
https://webflow.com/design

I hope you can review it and fix it.

Let me know if you need any additional information on the issue.

Thanks!

**Comment by nico2che** [comment]
Hi @arielcamino 

Sorry for my unclear message, I fixed this issue in the commit https://github.com/weglot/integration-hooks/commit/329c97bbe5b1ac2f3830cb6caede29d656ffab45 as shown by Github above my message, it should work now if you pull the new version.

`webflow.com/design` is not a link, it's the part of your URL you have to remove to find the right slug needed in `webflow/config.js`. I'm updating the README
